### ISSUE TITLE
一些反馈

### ISSUE THREAD

**Issue by lawrenceshi** [Littlefean/cyber-life#4]
我下载后遇到了无法运行的问题，以下是一些信息，供参考：

1. 运行EXE：

![image](https://github.com/Littlefean/cyber-life/assets/108813113/9e699e55-4891-4276-95c1-7fd6b7d3a8a2)
报错信息：
`Traceback (most recent call last):
  File "main.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "cyber_life\computer_info\manager.py", line 15, in <module>
  File "cyber_life\computer_info\manager.py", line 20, in _SystemInfoManager
  File "cyber_life\computer_info\inspector_memory.py", line 19, in __init__
  File "cyber_life\computer_info\inspector_memory.py", line 25, in inspect
  File "psutil\__init__.py", line 2036, in swap_memory
  File "psutil\_pswindows.py", line 266, in swap_memory
RuntimeError: PdhAddEnglishCounterW failed. Performance counters may be disabled.
`
2.下载python源码后也无法运行：
![image](https://github.com/Littlefean/cyber-life/assets/108813113/6a8bc54a-e161-474d-9889-4b8001f73ec7)
报错信息：
`Traceback (most recent call last):
  File "D:\下载\cyber-life-1.0.1\main.py", line 17, in <module>
    from cyber_life.computer_info.manager import SYSTEM_INFO_MANAGER
  File "D:\下载\cyber-life-1.0.1\cyber_life\computer_info\manager.py", line 15, in <module>
    class _SystemInfoManager(metaclass=SingletonMeta):
  File "D:\下载\cyber-life-1.0.1\cyber_life\computer_info\manager.py", line 20, in _SystemInfoManager
    INSPECTOR_MEMORY = InspectorMemory()
  File "D:\下载\cyber-life-1.0.1\cyber_life\computer_info\inspector_memory.py", line 19, in __init__
    self.inspect()
  File "D:\下载\cyber-life-1.0.1\cyber_life\computer_info\inspector_memory.py", line 25, in inspect
    psutil.swap_memory().percent / 100,
  File "C:\Users\shila\AppData\Local\Programs\Python\Python310\lib\site-packages\psutil\__init__.py", line 2036, in swap_memory
    return _psplatform.swap_memory()
  File "C:\Users\shila\AppData\Local\Programs\Python\Python310\lib\site-packages\psutil\_pswindows.py", line 266, in swap_memory
    percentswap = cext.swap_percent()
RuntimeError: PdhAddEnglishCounterW failed. Performance counters may be disabled.`

目前已排除：

- 库没装完（我看这个报错不像库没装完，前几次报错是库没装完，我一个一个装了）
- 未用管理员身份运行
- 未在C盘运行
- 路径里有中文
环境：

- python3.10.6
- win10专业版
- [AMD 560显卡](https://www.amd.com/zh-cn/support/downloads/drivers.html/graphics/radeon-600-500-400/radeon-rx-500-series/radeon-rx-560.html)

（以下信息从 系统 - 关于 复制而来）

设备名称	DESKTOP-OQE452V
处理器	AMD Ryzen 5 5600G with Radeon Graphics            3.90 GHz
机带 RAM	32.0 GB (31.8 GB 可用)
设备 ID	********-****-****-****-*********** (此处人工打码处理)
产品 ID	*****-*****-*****-*****(此处人工打码处理)
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

版本	Windows 10 专业版
版本号	22H2
安装日期	‎****/**/**(此处人工打码处理)
操作系统内部版本	19045.4412
体验	Windows Feature Experience Pack ****.*****.****.0 (此处人工打码处理)

**Comment by lawrenceshi** [comment]
好像确实漏了依赖（pynput）
通过`pip install -r requirements.txt`命令安装后
依然无法运行，报错一样

**Comment by Littlefean** [comment]
https://github.com/giampaolo/psutil/issues/2105

试一试以管理员身份运行的命令提示符输入 `lodctr /R` 看看行不行呢

**Comment by lawrenceshi** [comment]
好了！肥肠感谢！

**Comment by lawrenceshi** [comment]
建议可以在软件开始的时候用`os`库自动执行这个命令，我今天又无法进入了，每次多要输入命令挺烦的
外加还有一些建议写在这里：

1. 可以把小鱼的速度设为GPU的使用率
2. 可否加一些和音乐互动的内容
3. 可以加鼠标穿透吗？有时候要特地移开有点烦
4. 可以隐藏的图标吗？放到右下角的这个箭头上
5. 可以自定义一些内容吗？
-  比如说 ：
- 每上传几KB/MB的内容产生一个气泡，有时候我的气泡就很密集，看起来不太美观
- 自定义小鱼食物值掉的速度
- 每读取/写入几KB/MB的内容产生一个地震波
- 每空闲几MB的内存生成一个像素的水
- 以此类推...
6.  可不可以在多个桌面上显示，按win+tab会显示很多桌面（具体数量看你的创建，点击加号可以创建），但是赛博小鱼缸只会在一个桌面

**希望赛博小鱼缸做的更好**
_如果我有空闲时间的话我**也许**会发个PR改进一下_

@Littlefean

**Comment by Littlefean** [comment]
GPU性能指标我在考虑用其他的代替，不过好像不太好拿到，还有待试验
音效是有考虑的
鼠标穿透还没考虑过，正是想着尽量减少遮挡所以鱼缸设计的比较小，在2K分辨率下很小，但是好像在1080P下占用的体积还挺大的。在考虑分情况设置大小或者可以自定义
隐藏图标是个好主意

**Comment by lawrenceshi** [comment]
我想提个PR，请问该提交到tauri还是test呢？

**Comment by Littlefean** [comment]
> 我想提个PR，请问该提交到tauri还是test呢？

直接往主分支上提交吧，test太久远了，tauri是直接换了框架了。

**Comment by lawrenceshi** [comment]
![image](https://github.com/Littlefean/cyber-life/assets/108813113/9e3c5184-d3d4-47e0-9dcf-0b07476bb1ce)
好像 不好提

**Comment by lawrenceshi** [comment]
好了好了，是我不会提
